### ISSUE TITLE
RequestInteceptors and  ResponseCallback/RemoteCallback

### ISSUE THREAD

**Issue by abmancini** [errai/errai#195]
I have a very simple request interceptor like the following:

```
 @Override
    public void aroundInvoke(final RestCallContext context) {

        GWT.log("BEFORE CALL");
        context.proceed(
                response -> {
                    GWT.log("After CALL");
                    context.setResult(response);
                },
                (message, throwable) -> {
                    GWT.log("After CALL, with error response");
                  return true; //let the caller handle the real error
                }
        );
    }

```

what i see is that intercepted calls work if i call them providing a   "ResponseCallback" 
but not with a "RemoteCallback"

on the other hand if i define the interceptor as

```
@Override
    public void aroundInvoke(final RestCallContext context) {
        context.proceed(new RemoteCallback<Object>() {...}, 
                                  new ErrorCallback<Object>() {...});
   }

```

the calls work with RemoteCallback but not with ResponseCallback. 

With "not work"  i mean that i get errors in the browser console and the callback is never called (nor the error callback is called actually). 

I'm I misunderstanding how to use the interceptors ?

If needed i can try to provide a small repro case. 

Thanks.

**Comment by mbarkley** [comment]
Hi @abmancini,

In order to write a general purpose client-side interceptor it should implement `RemoteCallInterceptor<RemoteCallContext>` such that the `aroundInvoke` method has a `RemoteCallContext` as an argument.

[Here](https://github.com/errai/errai/blob/master/errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/interceptors/ClientSecurityRoleInterceptor.java) is an example used in Errai Security that works for `@Remote` interfaces and JAX-RS interfaces.

Hope that helps.

**Comment by abmancini** [comment]
Hi @mbarkley, 
thank you very much. 
I reworked the interceptor following your advice and now
the behaviour is more clear but unfortunately i still can't see the light.

I'm starting to think that my error is in how i use the remote service.

Even using the  ClientSecurityRoleInterceptor, I mean annotating my service with @RestrictedAccess(roles = "..." ) and configuring security accordingly, when i try to 
use a callback like:

 `
ResponseCallback rc = new ResponseCallback() {
            @Override

            public void callback(Response response) {
                Window.alert( "Response Text: " + response.getStatusText() + "Response code: "+ response.getStatusCode());
            }
        };
`

I get a "java.lang.ClassCastException" in the browser console. 

the actual call is:

`customerService.call(rc, errorCallback).retrieveCustomerById(12);`

The service itself is injected via IOC but the result does not change if i use RestClient.create(...).

Essentially for what i can understand the framework calls the callback with a Customer (the return type of my service) object and requiring the signature  of the callback a Response instead there is an attempt to coerce Customer to Response that cause the CastException. 

Any hint ? 

Thanks.

**Comment by mbarkley** [comment]
Hi @abmancini,

Can you share a reproducer for this? Would be happy to take a look.

Cheers,
Max

**Comment by abmancini** [comment]
Hello @mbarkley,
sorry for the delay but removing all the dependencies to have a minimal example required a bit of time. 

I uploaded a reproducer case here:
https://github.com/abmancini/interceptor-sample

just clone and execute mvn gwt:run.

The application consists of   just a page with two Anchors.

The first one execute a remote call using  a RemoteCallback and it works.
The second execute a remote call using  a ResponseCallback and fails (logs ClassCastException in the js console).

The service is annotated with @RestricedAccess and if you remove the annotation both calls  work as expected. 

Thanks,
    Alberto.

**Comment by mbarkley** [comment]
Thanks @abmancini. I'll take a look.

**Comment by mbarkley** [comment]
Hi @abmancini, I have looked into the problem and created this [JIRA issue](https://issues.jboss.org/browse/ERRAI-995). Unfortunately there is no quick fix, but I will be looking into a solution for this problem before our 4.0.0.Final release. Thanks again for the reproducer.

**Comment by mbarkley** [comment]
Hi @abmancini,

I've resolved this problem on master. The fix was to remove the ResponseCallback, as it is impossible to write a generic interceptor in any application that uses them.

As described in the JIRA, you can now use a `RemoteCallback<com.google.gwt.http.client.Response>` as a callback for JAX-RS RPC methods returning `javax.ws.rs.core.Response`. This allows you to get a response object for only methods returning a response. For other methods, it is no longer possible to get the underlying response.
