### ISSUE TITLE
Allow for Templated classes to be a Widget type

### ISSUE THREAD

**Issue by BenDol** [errai/errai#203]
This might already be possible, but I haven't been able to solve it.

Basically I want to be able to say that the root of my Templated is like so:
```xml
<div data-field="my-view">
    <div data-field="content"></div>
    ...
</div>
```

```java
@EntryPoint
@Templated("MyView.html#my-view")
public class MyView extends MaterialWidget {

    @Inject
    private Navigation navigation;

    @Inject @DataField
    private Div content;

    public MyView() {
        super(DOM.createDiv()); // calls setElement(element)
    }

    @PostConstruct
    protected void onPostConstruct() {
        content.add(navigation.getContentPanel());
        RootPanel.get().add(this);
    }
}
```

This doesn't work for me. Not sure if I have done something wrong but it makes sense that you can make the root of your Templated class as a Widget type.

Thanks!

**Comment by BenDol** [comment]
The result here is that it just has a `<div></div>` when this is run, even though my StartPage is set up to load (can post if needed, its doing the same thing as this with the `MaterialWidget`).

**Comment by BenDol** [comment]
Here are the [generated sources](https://www.mediafire.com/?fmnfb0s6g5adpsn) from the type that works (`Composite`) and where it doesn't work (`MaterialWidget`).

**Comment by mbarkley** [comment]
Hi @BenDol,

Extending a GWT widget type won't work except for `Composite` (which was how all `@Templated` beans were in Errai 3 and is only still supported for compatibility).

If you need your `@Templated` bean to work with GWT widgets, the best practice is to `@Inject` a widget `@DataField` mapped to the root element of your template and implement `IsWidget`, like so:

    @Inject @DataField("my-view") MaterialWidget root;

Now if you try that with `MaterialWidget` with the template above you may still encounter problems, because Errai will only add template content into a GWT widget `@DataField` if it implements `HasText`. So if `MaterialWidget` does not implement `HasText` (which I don't think it does) then your `<div data-field="content"></div>` will not be rendered inside the `MaterialWidget`.

Cheers.

**Comment by BenDol** [comment]
If a field can be injected as a widget what stops it from being marked as `@Templated` as a Widget? I know its probably not designed to work this way, but for me it would really help if it was. Since I want to build the templated classes as a "View" component that is attached to the view. Instead you are saying I need to inject it and then reference that injected container rather than the class itself if I want Widget interactions? (Such as addFocusHandler, addBlurHandler, etc). Perhaps this should be taken into consideration for 4.0.0?

**Comment by mbarkley** [comment]
Hi @BenDol,

I understand where you're coming from, but in Errai 4 the framework is moving away from GWT widget integration. Ideally we want users to always have element wrappers as `@DataFields`, but are allowing GWT widgets to be used for the purpose of gradual migration. so at present, being able to extend arbitrary GWT widgets with a `@Templated` class would not be a good fit for Errai.

This means you will have a bit more boilerplate to achieve what you want, but not so much. This is what I would try in your case:

    @EntryPoint
    @Templated("MyView.html#my-view")
    public class MyView implements IsWidget {
      @Inject @DataField("my-view") MaterialWidget root;

      @Override
      public MaterialWidget asWidget() {
        return root;
      }
    }

In the end, this just means that instead of `templated.addFocusHandler(...)` you will have to do `templated.asWidget().addFocusHandler(...)`.

**Comment by BenDol** [comment]
Thank you for your time @mbarkley appreciate it.

**Comment by BenDol** [comment]
Is it possible to get the root `DataField` by default without specifying the name in the `@Templated`? So my views will default use the root element as the root Widget?

**Comment by BenDol** [comment]
For some reason, doing it this way won't render the content of my default Page (or any page for that matter). I end up with this:
```html
<div>
    <main data-field="content">
        <div class="navigation">
            <div data-field="view" class="center-align" style="margin-top: 15%;" tabindex="-1"></div>
        </div>
    </main>
</div>
```

`data-field="view"` is the default Page div, but it has 4 children that it should be rendering, however for some reason they are not rendered.

**Comment by BenDol** [comment]
Filed the issue https://issues.jboss.org/projects/ERRAI/issues/ERRAI-1001?filter=allopenissues

**Comment by mbarkley** [comment]
Hi @BenDol,

This is not a bug. Errai would only render your `Button` inside the `MaterialWidget` if the latter implemented `HasText` (which I don't believe is the case). Furthermore, if `MaterialWidget` did implement `HasText` we would still not call `add` on your `MaterialWidget` because the composition happens via the HTML hiearchy.

When Errai builds your component, it traverses your template fragment and replaces elements in the template with the elements returned by `Widget.getElement()` of the respective `@DataFields`. If the respective `Widget` happens to implement `HasText` then Errai will add all the children of the template element to the widget's element -- *but this is all done through the DOM API and not the widget API*.

**Comment by BenDol** [comment]
So to resolve the issue MaterialWidget needs to support HasText which would be doing what exactly?

**Comment by mbarkley** [comment]
Yeah exactly, `HasText` just signifies that this is a kind of widget in which we can add markup, unlike a `TextBox` for example.
