### ISSUE TITLE
Question : CDI Event not working

### ISSUE THREAD

**Issue by kevzlou7979** [errai/errai#211]
Hi there,

CDI Event is not firing when class is not annotated by @Page?

I tried to create a Widget (Encapsulate it from my Page) so I separated it. On my Widget I added
```
public class MyWidget {
   @Inject
   Event<MyEvent> myEvent;

   @PostConstruct
   public void init() {
           myEvent.fire(new MyEvent());
   }
}
```

Then on MyPage I added a method to observe the event.

```
@Page
public class MyPage {

   public void observeMyEvent(@Observes event) {
       GWT.log("Event Fired"); // does not work.
   }
}
```
Can you explain why the event is not firing on separate class?

**Comment by mbarkley** [comment]
Hi @kevzlou7979,

There's not enough information here for me to know for certain, but I'm guessing you are injecting `MyWidget` into `MyPage`? If that is the case, then `MyWidget` will be created first (since `MyPage` depends on it) meaning its event will fire before `MyPage` is ready to observe events.
